# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Minor updates for npm in root directory
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      dev-deps:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      prod-deps:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'

  # Major updates for npm in root directory
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
    groups:
      dev-deps-major:
        dependency-type: 'development'
        update-types:
          - 'major'
      prod-deps-major:
        dependency-type: 'production'
        update-types:
          - 'major'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      prod-deps:
        patterns:
          - '*'

  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      prod-deps:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      dev-deps:
        patterns:
          - '*'
