services:
  # Nginx Reverse Proxy
  rp:
    image: nginx:1.31.0@sha256:06aa3d7be10bc6307990c81bdca075793132e9163391abc370c015e344e23128
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - th
    restart: unless-stopped

  th:
    build:
      context: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
