services:
  # Nginx Reverse Proxy
  rp:
    image: nginx:1.31.4@sha256:25ee11a13a12120be02c56b9606fde6ffeeb3dff002a9e072c4a2611ab5fd995
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - th
    restart: unless-stopped

  th:
    image: ghcr.io/baipyrus/terminal-homepage:main
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: 'production'
    restart: unless-stopped
