services:
  # Nginx Reverse Proxy
  rp:
    image: nginx:1.31.3@sha256:8541484afbc9c8a5a8a99b379568ebbc957f658583ec9448fc43104229c03cf8
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - th
    restart: unless-stopped

  th:
    image: ghcr.io/baipyrus/terminal-homepage:main
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: 'production'
    restart: unless-stopped
