# WARN: This workflow is entirely discouraged because of the simple reason that this
#       project doesn't support building without production ready secrets (see step
#       "prepare production environment" below). Since this environment gets saved
#       to a file within the image itself, a publicly accessible image would leak
#       all secrets within it. The only known solutions without changing the project
#       structure and build process is to provide private images only or build
#       the project on the server yourself.

name: Publish Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare production environment
        run: |
          tee --append .env <<'EOF' >/dev/null
          # Drizzle
          DATABASE_URL=${{ secrets.DEPLOY_DB_PATH }}

          ORIGIN="${{ secrets.DEPLOY_ORIGIN }}"

          # Better Auth
          BETTER_AUTH_SECRET="${{ secrets.DEPLOY_BETTER_AUTH }}"

          # GitHub OAuth
          GITHUB_CLIENT_ID="${{ secrets.DEPLOY_OAUTH_ID }}"
          GITHUB_CLIENT_SECRET="${{ secrets.DEPLOY_OAUTH_SECRET }}"
          EOF

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about)
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a subsequent step.
      # The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built.
      # It increases supply chain security for people who consume the image. For more information, see
      # [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Generate artifact attestation
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
