# WARN: This workflow is entirely discouraged because of the simple reason that this
#       project doesn't support building without production ready secrets (see step
#       "prepare production environment" below). Since this environment gets saved
#       to a file within the image itself, a publicly accessible image would leak
#       all secrets within it. The only known solutions without changing the project
#       structure and build process is to provide private images only or build
#       the project on the server yourself.

name: Publish Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare production environment
        run: |
          tee --append .env <<'EOF' >/dev/null
          # Drizzle
          DATABASE_URL=${{ secrets.DEPLOY_DB_PATH }}

          ORIGIN="${{ secrets.DEPLOY_ORIGIN }}"

          # Better Auth
          BETTER_AUTH_SECRET="${{ secrets.DEPLOY_BETTER_AUTH }}"

          # GitHub OAuth
          GITHUB_CLIENT_ID="${{ secrets.DEPLOY_OAUTH_ID }}"
          GITHUB_CLIENT_SECRET="${{ secrets.DEPLOY_OAUTH_SECRET }}"
          EOF

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about)
      # to extract tags and labels that will be applied to the specified image.
      # The `id` "meta" allows the output of this step to be referenced in a subsequent step.
      # The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built.
      # It increases supply chain security for people who consume the image. For more information, see
      # [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Generate artifact attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
